#redis相关
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 30s
#    password:

#dubbo相关-消费者
dubbo:
  scan:
    base-packages: com.edison.springCloudAlibabaDemo.service # 指定 Dubbo 服务实现类的扫描基准包
  # Dubbo 服务暴露的协议配置，对应 ProtocolConfig Map
  protocols:
    dubbo:
      name: dubbo # 协议名称
      port: -1 # 协议端口，-1 表示自增端口，从 20880 开始
  # Dubbo 服务注册中心配置，对应 RegistryConfig 类
  registry: #使用 spring.cloud.nacos.discovery 配置项的 Nacos 注册中心
    address: spring-cloud://127.0.0.1:8848 # 指定 Dubbo 服务注册中心的地址
  # Spring Cloud Alibaba Dubbo 专属配置项，对应 DubboCloudProperties 类
  cloud:
    subscribed-services: '' # 设置订阅的应用列表，默认为 * 订阅所有应用