################
##配置都在nacos上
################
git:
  client_id: 76010f96ba5380e16c13
  client_secret: b1d17709b531d64646d7cb0d08e6a2755db2d909
#redis相关
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 30s
#    password:
